export const REQUEST_RESTAURANTS = "REQUEST_RESTAURANTS";
export const RECEIVE_RESTAURANTS = "RECEIVE_RESTAURANTS";
export const SET_QUERY_PARAMS = "SET_QUERY_PARAMS";
export const SET_HOME_VIEW = "SET_HOME_VIEW";
export const SET_RESULTS_VIEW = "SET_RESULTS_VIEW";